### ISSUE TITLE
Remove entries() limitation

### ISSUE THREAD

**Issue by leventov** [OpenHFT/Chronicle-Map#105]
Remove necessity to specify `entries()` on Chronicle Map configuration without significant penalty even if the data structure grows by many times, e. g. from 1 to 100 millions of entries.

**Comment by minborg** [comment]
@RobAustin can we close this issue?

**Comment by RobAustin** [comment]
Setting to "won't fix" and closing.

**Comment by fgoepel** [comment]
Is there a rationale for this somewhere? It's a bit of shame, as it basically disqualifies ChronicleMap from any use case with continuous data growth that can't just be pre-provisoned. LMDB and libmdbx appear to handle this well enough by having a fixed map with an expansion step instead of the perfomance footgun ChronicleMap seems to exhibit in such a case. (Correct me if I'm wrong here.)

**Comment by minborg** [comment]
@shado23 Having a pre-allocated fixed layout improves performance, determinism and reduces complexity. Feel free to submit a PR with dynamic resizing.
