### ISSUE TITLE
ClassCastException: Byteable

### ISSUE THREAD

**Issue by kalgm** [OpenHFT/Chronicle-Map#110]
When using the @Array annotation in an interface, I get a ClassCastException: Bytable when trying to put a value into the map. It works for long[] but fails for double[]. Using chronicle-map 3.12.0

java.lang.ClassCastException: com.test.Test cannot be cast to net.openhft.chronicle.bytes.Byteable
	at net.openhft.chronicle.hash.serialization.impl.ByteableDataAccess.getData(ByteableDataAccess.java:27)
	at net.openhft.chronicle.map.VanillaChronicleMap.put(VanillaChronicleMap.java:713)

ITest Interface:
public interface ITest {
    @Array(length=100)
    double getData2At(int index);
    void setData2At(int index, double data);
}

**Comment by leventov** [comment]
@kalgm could you please post a full reproducible test?

**Comment by kalgm** [comment]
`
import net.openhft.chronicle.values.Array;

interface IContainer {
    @Array(length=10)
    double getDoubleArrayAt(int i);
    void setDoubleArrayAt(int i, double d);
}`

`
import net.openhft.chronicle.map.ChronicleMap;
import net.openhft.chronicle.map.ChronicleMapBuilder;
import org.junit.Test;

public class TestChronicleDoubleArray {

    private static class Container implements IContainer {
        private double[] doubleArray = new double[10];

        @Override
        public double getDoubleArrayAt(int i) {
            return doubleArray[i];
        }

        @Override
        public void setDoubleArrayAt(int i, double d) {
            doubleArray[i] = d;
        }
    }

    @Test
    public void testChronicleDoubleArray() {
        ChronicleMap<String, IContainer> map =
                ChronicleMapBuilder.of(String.class, IContainer.class)
                        .entries(1024)
                        .averageKeySize(9)
                        .create();

        map.put("0", new Container());
        assert map.get("0") != null;
    }
}`

**Comment by leventov** [comment]
@kalgm thank you. There was a bug in Chronicle Values, fixed in version 1.5.4. Before the next version of Chronicle Map is released, you can specify an updated Chronicle Values dependency manually in your project, along with Chronicle Map dependency.

Also note that manual implementation of `Container` is not needed, Chronicle Values does this for you if you call `Values.newHeapInstance(IContainer.class)`. See https://github.com/OpenHFT/Chronicle-Map/blob/75b91a4142cf2d88f170e3d63eee64dad542d8cc/src/test/java/net/openhft/chronicle/map/Issue110Test.java

**Comment by leventov** [comment]
This bug is fixed in Chronicle Map 3.13.0
