### ISSUE TITLE
All checksums are zero.

### ISSUE THREAD

**Issue by pirocks** [OpenHFT/Chronicle-Map#118]
I'm creating/recovering a chronicle map with:
`Historical.orders = ChronicleMap`
`                        .of(Integer.class, LimitOrder.class)`
`                        .name("the-historical-orderbook")`
`                        .entries(100_000).valueSizeMarshaller(new ConstantSizeMarshaller(5000L))`
`                        .checksumEntries(true)`
`                        .createOrRecoverPersistedTo(new File("historical-orders.bin"));`

Whenever recover an instance of a chronicle map with the above. All of my entries have a checksum of zero, and therefore they are all interpreted as corrupted. This happens on windows 10/ubuntu/debian.

**Comment by leventov** [comment]
Could you prepare a complete reproducible example?

**Comment by pirocks** [comment]
See:https://github.com/pirocks/reproducible

**Comment by leventov** [comment]
This happens because the size of the values that you store in the Chronicle Map is not 5000. What did you want to achieve by configuring `.valueSizeMarshaller(new ConstantSizeMarshaller(5000L))`?

`ConstantSizeMarshaller` is an internal class and shouldn't be used in the client code. Use `.constantValueSizeBySample(new Thing())` instead. Note that `.constantValueSizeBySample()` is valid when values *are serialized into streams of bytes of the same length*, but not if values are "equal" or "constant" in any other sense.

Also note that `Serializable` classes are supported inefficiently in Chronicle Map at the moment, and if you don't want to be disappointed by Chronicle Map's performance, at least make the values to implement `BytesMarshallable`, or provide [custom serializers](https://github.com/OpenHFT/Chronicle-Map#custom-serializers).

**Comment by leventov** [comment]
And in your reproducible example `.constantValueSizeBySample(new Thing())` is wrong, because `Thing` objects are serialized into sequences of bytes of *different lengths*.

**Comment by pirocks** [comment]
Oh I see thanks for the help.
