### ISSUE TITLE
how to clear chronicle map really?

### ISSUE THREAD

**Issue by hxwabc** [OpenHFT/Chronicle-Map#128]
on remove or clear chronicle map, it just marked it. how to clear chronicle map really?

**Comment by leventov** [comment]
Just marking deleted entries instead of removing them is the thing of replicated version of Chronicle Map, that is not available in public. In open-source version, entries are deleted properly. Also Chronicle Map is configured with some size from the beginning and there is no way to "shrink" map to take less space, if you ask for it.

**Comment by RobAustin** [comment]
closing as I feel this has been answered.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.17.3](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.17.3), [BOM-2.17.262](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.262)
