### ISSUE TITLE
Maximum size of Chronicle Map file

### ISSUE THREAD

**Issue by osnatn1984** [OpenHFT/Chronicle-Map#130]
Hi,

I need to create very big Chronicle map file, that will includes 650 million entries. How this can be done?
When I tried to set the estimated entries to 650,000,000 - it just stuck in the creation of the chronicle map.
When I tried to set a lower number of entries, 5,000,000 for example - It creates the file but it crashes around 9,000,000.
Is is possible to create such a big Chronicle Map? 
If it is - what is the right way to do it?
If it doesn't - when is the maximum size of chronicle map that is valid?

Thanks,
Osnat

**Comment by leventov** [comment]
What entry size do you configure? Operation system? Machine characteristics (memory, disk)?

**Comment by osnatn1984** [comment]
The entry size is 56 Gb

OS: CentOs 7
Memory: 24 Gb physical ram, 12 Gb swap
Disk: 1.7 T

When I tried to create a Chronicle Map with 5,000,000 estimated entries – this is what I got:

2017-07-02 11:54:53,057 ERROR [Thread-1] [com.xconnect.np.view.builder.views.PortabilityViewBuilder] - Fail to create view.
java.lang.IllegalStateException: ChronicleMap{name=null, file=/XC/views_1010/portabilityevents_US3418599014265244323, identityHashCo
de=1104054943}: Attempt to allocate #1025 extra segment tier, 1024 is maximum.

When I tried to create a Chronicle Map with 100,000 estimated entries – this is what I got:

ava.lang.IllegalStateException: ChronicleMap{name=null, file=/XC/views_1010/portabilityevents_US2277284071811422737, identityHashCode=765071901}: Attempt to allocate #33 extra segment tier, 32 is maximum.

Any ideas?

Thanks,
Osnat.

**Comment by leventov** [comment]
Entry size couldn't be 56 Gb.

Either you put much more entries into the Chronicle Map than you configure, or put much large entries than you configure. Messages like "Attempt to allocate #1025 extra segment tier, 1024 is maximum." point to that.

**Comment by osnatn1984** [comment]
56Gb is the size of the file created when the estimated entries are 800,000,000. However, updates to a file that size were so slow that it took 20 minutes to get a mere 200,000 entries into the file.
in order to test at what point things break, we reconfigured the estimated entries to be only 5,000,000 but the process broke down once there were 9,000,000 records entered with the error:
"Attempt to allocate #1025 extra segment tier, 1024 is maximum."

it seems you must pre-configure the file to at least 1/2 the size that it will end up being. is there a way to let the file expand indefinitely? Is there a maximum size that is the most efficient for a map file?
We think that 56 Gb may never work properly so we may decide to break up the entries into multiple files. Are there general guidelines for this?

**Comment by leventov** [comment]
@osnatn1984 

> it seems you must pre-configure the file to at least 1/2 the size that it will end up being

Actually you should configure the map to 100% +- 10% of what it will end up being. Putting more entries beyond the configured `ChronicleMapBuilder.entries()` is functionally supported, but slow. "1/2 of the size" that you observed is because the default configuration of [`maxBloatSize()`](http://static.javadoc.io/net.openhft/chronicle-map/3.13.0/net/openhft/chronicle/hash/ChronicleHashBuilder.html#maxBloatFactor-double-) is 1.0. If you configure it to 4.0, and configure `X` entries, you will be able to insert a bit less than `5 * X` entries before it will fail with IllegalStateException. But, again, it will be very slow.

The conceptual solution allowing infinite growth without performance degrading is possible (#105) and even under the way, but no promises when it will be complete.

Note that Chronicle Map is not designed for out-of-memory workloads: in your case it's 56 GB of the Map and only 24 GB of memory (and even less available for the map itself, likely). If this machine configuration is something that you definitely cannot change, I recommend you to consider other storages, e. g. LMDB or RocksDB. But if the ChronicleMap can fully reside in memory, it performs better than the other stores on random access.

**Comment by minborg** [comment]
I am closing this issue now @osnatn1984. From a performance perspective, having more RAM than the map itself occupies is a good thing.
