### ISSUE TITLE
Error on removing from replicated map

### ISSUE THREAD

**Issue by hani** [OpenHFT/Chronicle-Map#26]
I have two nodes running that are replicating to each other. The map is of type string/string. The store config is:

ChronicleMapBuilder
                                 .of(String.class, String.class)
                                 .entries(5000)
                                 .averageValueSize(8000)
                                 .replication(<1 or 2, depending on the host, tcpConfig)
                                 .createPersistedTo(file)

TCP config is used with heartbeat interval of 5, and no throttling. All other values are their defaults.

The load test fires about 12k messages on the primary node. The node deletes a message once it processes it, so it never gets to above 1000 or so. The insertion and deletion happen on separate threads.

I will eventually get this exception on the primary:

java.lang.IllegalStateException
        at net.openhft.chronicle.map.ShortShortMultiMap.nextPos(ShortShortMultiMap.java:227)
        at net.openhft.chronicle.map.ReplicatedChronicleMap$Segment.removeWithoutLock(ReplicatedChronicleMap.java:1106)
        at net.openhft.chronicle.map.ReplicatedChronicleMap$Segment.remove(ReplicatedChronicleMap.java:1051)
        at net.openhft.chronicle.map.VanillaChronicleMap.remove(VanillaChronicleMap.java:1109)
        at net.openhft.chronicle.map.VanillaChronicleMap.removeIfValueIs(VanillaChronicleMap.java:1046)
        at net.openhft.chronicle.map.VanillaChronicleMap.remove(VanillaChronicleMap.java:934)

This is using 2.1.10. Previously when running 2.1.2, I'd get a similar exception but on the TCP replicator thread on the secondary.

**Comment by BoundedBuffer** [comment]
Hani

Thanks for your bug report. Could you send me a test case that reproduces this issue.  Thanks. 

Rob

**Comment by BoundedBuffer** [comment]
JIRA raised - https://higherfrequencytrading.atlassian.net/browse/HCOLL-343 <https://higherfrequencytrading.atlassian.net/browse/HCOLL-343>

**Comment by leventov** [comment]
@hani This IllegalStateException indicates that the internal hash table is full.

The thing is, as of now, ChronicleMap in replicated mode doesn't actually purge deleted entries, it just marks them as "deleted". This is because "the fact of deletion" also should be replicated, and we should keep information about the moment the key was deleted at, to discard late inserts with the same key. If you eventually delete some keys and add new, the map eventually become overflowed with stale deleted entries.

*Right now* this problem has no resolution. We consider some ways to resolve it:

 - Introduce some clean up thread, which walks through the map and purges entries, marked as deleted and which was not updated "for long time". The main weakness of that "the long time" is loosely specified and probably couldn't be specified 100% correctly, in case of net splits etc.. doubled heart beat? Here is a Jira issue for that: https://higherfrequencytrading.atlassian.net/browse/HCOLL-227

 - Allow to specify somehow that keys in the distributed system are updated in "one direction", i. e. couldn't be inserted on any node, after being deleted on one of the replicated nodes.

However, in your case, it is probable that you don't need the replicated nodes at all:
 - Seems that you always add entries on one node and remove on another. Probably you need stateless client instead of replicated nodes, when you can add the entry "remotely".

 - You mentioned that "The node deletes a message once it processes it", if your entries (keys/values) are "messages" and your somewhat "processes" them in some order, looks like Chronicle Queue data structure fits better for this task. Chronicle Queue also has replication; also has remote calls; obviously it doesn't have overflow problems, because unlike Chronicle Map it can grow infinitely.

I'm closing this issue, because it doesn't have immediate resolution; you can expect some updates probably to this isuue: https://higherfrequencytrading.atlassian.net/browse/HCOLL-227

**Comment by hani** [comment]
Hi Rob, thanks for the update.

Having a thread that runs periodically that removes entries that are 'deleted' would fix the issue for me. I'm not writing and deleting on different nodes, there is only ever 1 node active which gets all writes and deletes. The 2nd node is a failover node (so at any point, only one node has all ops performed against it).

Unfortunately I don't have ordering, messages that get deleted are deleted by key, not sequentially.

So is there any way of having a cleanup process that walks the map and fully deletes entries that were removed via map.remove? Or compacts the file down to the entries that are actually live?
