### ISSUE TITLE
Wildfly Module

### ISSUE THREAD

**Issue by pratikpparikh** [OpenHFT/Chronicle-Map#34]
When included as JBoss Module I get the following from Chronicle Map?

Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) [rt.jar:1.8.0_25]
        at net.openhft.chronicle.map.ChronicleMapBuilder.deserializeHeaderViaXStream(ChronicleMapBuilder.java:1450)
        ... 12 more
Caused by: com.thoughtworks.xstream.io.StreamException: Cannot create XmlPullParser
        at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:56)
        at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:65)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1070)
        ... 17 more

**Comment by BoundedBuffer** [comment]
Which version of chronicle map are you using ?

**Comment by pratikpparikh** [comment]
latest snapshort

On Wed, Aug 5, 2015 at 7:08 AM, Rob Austin <notifications@github.com> wrote:

> Which version of chronicle map are you using ?
>
> > On 5 Aug 2015, at 11:54, pratikpparikh <notifications@github.com> wrote:
> >
> > When included as JBoss Module I get the following from Chronicle Map?
> >
> > Caused by: java.lang.reflect.InvocationTargetException
> > at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [rt.jar:1.8.0_25]
> > at
> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [rt.jar:1.8.0_25]
> > at
> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [rt.jar:1.8.0_25]
> > at java.lang.reflect.Method.invoke(Method.java:483) [rt.jar:1.8.0_25]
> > at
> net.openhft.chronicle.map.ChronicleMapBuilder.deserializeHeaderViaXStream(ChronicleMapBuilder.java:1450)
> > ... 12 more
> > Caused by: com.thoughtworks.xstream.io.StreamException: Cannot create
> XmlPullParser
> > at
> com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:56)
> > at
> com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:65)
> > at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1070)
> > ... 17 more
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/OpenHFT/Chronicle-Map/issues/34>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenHFT/Chronicle-Map/issues/34#issuecomment-127956430>
> .
>



-- 
Pratik Parikh
- Mantra - Keep It Simple and Straightforward

**Comment by RobAustin** [comment]
I suggest you use 

net.openhft <http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22net.openhft%22>	chronicle-map <http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22chronicle-map%22>	2.2.2 <http://search.maven.org/#artifactdetails%7Cnet.openhft%7Cchronicle-map%7C2.2.2%7Cjar>	03-Aug-2015	pom <http://search.maven.org/remotecontent?filepath=net/openhft/chronicle-map/2.2.2/chronicle-map-2.2.2.pom>  jar <http://search.maven.org/remotecontent?filepath=net/openhft/chronicle-map/2.2.2/chronicle-map-2.2.2.jar>  javadoc.jar <http://search.maven.org/remotecontent?filepath=net/openhft/chronicle-map/2.2.2/chronicle-map-2.2.2-javadoc.jar>  sources.jar <http://search.maven.org/remotecontent?filepath=net/openhft/chronicle-map/2.2.2/chronicle-map-2.2.2-sources.jar>  


rather than the alpha

net.openhft <http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22net.openhft%22>	chronicle-map <http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22chronicle-map%22>	3.1.3-alpha <http://search.maven.org/#artifactdetails%7Cnet.openhft%7Cchronicle-map%7C3.1.3-alpha%7Cbundle>  all (45) <http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22net.openhft%22%20AND%20a%3A%22chronicle-map%22>	02-Jul-2015	pom <http://search.maven.org/remotecontent?filepath=net/openhft/chronicle-map/3.1.3-alpha/chronicle-map-3.1.3-alpha.pom>  jar <http://search.maven.org/remotecontent?filepath=net/openhft/chronicle-map/3.1.3-alpha/chronicle-map-3.1.3-alpha.jar>  javadoc.jar <http://search.maven.org/remotecontent?filepath=net/openhft/chronicle-map/3.1.3-alpha/chronicle-map-3.1.3-alpha-javadoc.jar>  sources.jar <http://search.maven.org/remotecontent?filepath=net/openhft/chronicle-map/3.1.3-alpha/chronicle-map-3.1.3-alpha-sources.jar>

**Comment by pratikpparikh** [comment]
I have used it and it does not change anything.

**Comment by domdorn** [comment]
this blog post might be related
http://blog.siteos.de/java/javaee/chroniclemap/2016/05/16/How-To-Use-ChronicleMap-With-JavaEE.html

**Comment by leventov** [comment]
@domdorn in this case it might be fixed in Chronicle Map 3.12.0 for non-value interface keys and values, because 3.12.0 "ports" the fix from that blog post: https://github.com/OpenHFT/Chronicle-Map/releases/tag/chronicle-map-3.12.0

**Comment by RobAustin** [comment]
closing as we no longer provide support to chronicle map v2
