### ISSUE TITLE
File size increases along with increasing the number of processes and finally causes Error:Segment is full or has no ranges of 34 continuous free chunks

### ISSUE THREAD

**Issue by xfeep** [OpenHFT/Chronicle-Map#39]
```shell
## 1 process
$ du -h /tmp/shared-1k.map 
124M	/tmp/shared-1k.map

## 2 processes
$ du -h /tmp/shared-1k.map 
224M	/tmp/shared-1k.map

## 3 processes
$ du -h /tmp/shared-1k.map 
311M	/tmp/shared-1k.map

## 4 processes
Error :
```

The Error stack 
```java
Exception in thread "main" java.lang.IllegalStateException: Segment is full or has no ranges of 34 continuous free chunks
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.alloc(VanillaChronicleMap.java:2433)
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.putEntry(VanillaChronicleMap.java:2372)
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.putWithoutLock(VanillaChronicleMap.java:2285)
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.put3(VanillaChronicleMap.java:2237)
	at net.openhft.chronicle.map.VanillaChronicleMap.put2(VanillaChronicleMap.java:607)
	at net.openhft.chronicle.map.VanillaChronicleMap.put1(VanillaChronicleMap.java:592)
	at net.openhft.chronicle.map.VanillaChronicleMap.put(VanillaChronicleMap.java:550)
	at testhugcollection.ChronicleMapDemo.main(ChronicleMapDemo.java:41)
```

Testing Source
```java
package testhugcollection;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.ByteBuffer;
import java.util.Map;
import java.util.UUID;

import net.openhft.chronicle.map.ChronicleMapBuilder;
//import net.openhft.chronicle.map.MapEventListener;
import net.openhft.lang.io.Bytes;

public class ChronicleMapDemo {

	public ChronicleMapDemo() {
	}

	public static void main(String[] args) throws IOException {

		String tmpdir = System.getProperty("java.io.tmpdir");
		ChronicleMapBuilder<String, String> builder = ChronicleMapBuilder.of(
				String.class, String.class);
		
		StringBuilder ls = new StringBuilder();
		for (int i = 0; i < 1024; i++) {
			ls.append("a");
		}
		String lss = ls.toString();
		
//		builder.constantValueSizeBySample(lss).entries(100000); // set the max number of entries here
		File sf = new File(tmpdir + "/shared-1k.map");
		Map<String, String> map = builder.createPersistedTo(sf);

		do {
			long start = System.currentTimeMillis();
			String[] keys = new String[100000];
			for (int i = 0; i < 100000; i++) {
				String k = keys[i] = UUID.randomUUID().toString();
				map.put(k, lss);
			}
			System.out.println("size:" + map.size() + "file size:"
					+ sf.length());
			System.out
					.println("w cost " + (System.currentTimeMillis() - start));

			start = System.currentTimeMillis();
			String val = "";
			for (int i = 0; i < 100000; i++) {
				val = map.get(keys[i]);
			}
			System.out.println(val);
			System.out.println("size:" + map.size() + "file size:"
					+ sf.length());
			System.out
					.println("r cost " + (System.currentTimeMillis() - start));

			start = System.currentTimeMillis();
			for (int i = 0; i < 100000; i++) {
				val = map.remove(keys[i]);
			}

			System.out.println(val);
			System.out.println("size:" + map.size() + "file size:"
					+ sf.length());
			System.out
					.println("d cost " + (System.currentTimeMillis() - start));
		} while (true);

	}
}

```
Testing Environment

```shell
$java -version
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)

$uname -a
Linux  3.13.0-63-generic #103-Ubuntu SMP Fri Aug 14 21:42:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```shell
##chronicle-map version
[net.openhft/chronicle-map "2.3.3"]
```

**Comment by leventov** [comment]
Chronicle Map 2 is not resizable, it has a hard limit of entries could be put into the data store, configured by `entries(N)` call on ChronicleMapBuilder. If you omit this configuration, it defaults to 1 million, but the limit still exists.

BTW when released Chronicle Map 3 won't have this limitation, but `entries(N)` is still must-to-configure in Chronicle Map 3. It won't fail on "overflow" but performance decrease badly.

Also, unless your keys and/or values are of statically known constant size (like primitives) you must configure `averageKeySize()` or `constantKeySizeBySample()` or `averageKey()` and respecitively for values, on ChronicleMapBuilder.

File size increases as the Chronicle Map increases, because it allocates disk and memory space lazily on Linux (but not Windows).

**Comment by xfeep** [comment]
Hi, Leventov, Thanks for your quick response!
After I add
```java
builder.constantKeySizeBySample(..).constantValueSizeBySample(..).entries(..);
```
it runs perfectly!

I plan to use it to implement an inter-processes session store in my opensource project [Nginx-Clojure](https://github.com/nginx-clojure/nginx-clojure), e.g.  a session store shared by Nginx worker processes on the same machines. Keys are constant size string and the maximum length of values is 64k.

Are there any other limitations about Chronicle Map in my case?  

Another question is how to know the original configurations such as key-size, value-size, entries-number after the process restart?  I found that if we change configurations , e.g. with a larger number of entries , but an old file was created by old configurations and when more records (the maximum number is less than new configuration but larger than old one)  are added  it will reach error  `Segment is full, no free entries found` .

Thanks in advance!

**Comment by leventov** [comment]
@xfeep 

> Are there any other limitations about Chronicle Map in my case?

I don't see such. If you encounter problems you could reach us asking questions on [chronicle google group](https://groups.google.com/forum/#!forum/java-chronicle).

> Another question is how to know the original configurations such as key-size, value-size, entries-number after the process restart?

There is no way to query these numbers from Chronicle Map read from existing file. Currently there is no way to "reconfigure" an existing map, increasing number of entries. Good news is that if you run on Linux and you have that large entries (up to 64k, as you mentioned) you could configure `entries()` with unrealistically large number from the start, and it won't hurt memory footprint or performance, because Chronicle Map allocates memory lazily on demand.
