### ISSUE TITLE
ChronicleMap with ChronicleMap<String,HashSet<Integer>> errors

### ISSUE THREAD

**Issue by ebaysteve** [OpenHFT/Chronicle-Map#46]
I am working on a very large data set (50 million rows with 10 elements in each row) where we are trying to store it as a MultiMap<String, Integer>.  Where the String is the unique key and the Integer holds a set of id's.  For the majority of the keys there will be 1-5 Integer elements, however there are some that can spike it up to 10000 integers per key that would need to be stored in the nested hash map.  

I have tried playing around with the average key size and average value size along with the initial size but I keep getting errors . 

The most common error is Segment is full or has no ranges of 15 continuous free chunks
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.alloc

I tried to switch the Java HashMap to a guave MultiSet and received the following error:
java.lang.IllegalStateException
	at net.openhft.chronicle.map.ShortShortMultiMap.nextPos(ShortShortMultiMap.java:225) 

I can create a quick code sample and some test cases if that would help.

Just wondering if ChronicleMap supports this level of data without knowing really how much we are going to need to store each value per key in the ChronicleMap.

**Comment by leventov** [comment]
You are using Chronicle Map 2 which has shortcomings especially in the field you are exploring: variable-sized values.

Chronicle Map 3 is on the release track, but the latest current state available on Maven is quite outdated. Next alpha/beta releases are coming soon, but for now I suggest you to build Chronicle Map from source.

Then,
You should configure 4 numbers in `ChronicleMapBuilder`: `actualChunkSize()`, `actualSegments()`, `actualChunksPerSegment()` and `entriesPerSegment()`.

Choose `actualChunkSize` depending on how much memory are you ready to lose due to internal fragmentation.

Choose `actualSegments` a power of two, preferably > 4 * actual concurrent threads accessing Chronicle Map, if this number is > 1.

Choose `entriesPerSegment` so that

 - If `actualAverageEntriesPerSegment` is the actual (expected) total number of entries stored in the Chronicle Map, divided by `actualSegments`, Poisson CDF with mean of `actualAverageEntriesPerSegment` and argument `entriesPerSegment` should >> 1. E. g. 0.9999+

- `entriesPerSegment` multiplied by the actual average entry size (depends on your keys size and the actual distribution of number of integer elements in the values) should be at least several `mmap` page sizes, again the actual number depends on how much memory you are ready to lose due to external fragmentation.

The above recommendations contradict to each other to some degree, so satisfying them all might be not possible, here you should find a tradeoff.

Finally choose `actualChunksPerSegment` = `entriesPerSegment` * the actual average entry size (see above) / `chunkSize`.

This should work pretty fine.

**Comment by ebaysteve** [comment]
Thanks that worked.  Appreciate the assistance.

**Comment by leventov** [comment]
@ebaysteve BTW Chronicle Map 3.1.4 is now released, and you could use it instead of building Chronicle Map 3 locally (if you did that).
