### ISSUE TITLE
Expected release date for version 3?

### ISSUE THREAD

**Issue by metabrain** [OpenHFT/Chronicle-Map#47]
Hey,

Any expected release date for the 3.1/2.X version? 

We are updating our chronicle-map versions from 1.X and 2.X, and wanted to look into the new features provided by version 3 as detailed leventov here (http://stackoverflow.com/questions/29829835/chronicle-map-value-data-types), but we currently have no idea of the current state of the alpha. Tried checking the googleforum and Chronicle JIRA but haven't see many tickets referencing version 3, only 2.3.X and 2.1.X.

Thanks in advance,
Parreira

**Comment by leventov** [comment]
Thanks for interest.

Chronicle Map 3.1.4-alpha is just released, it includes 3-month improvements since 3.1.3-alpha. You could get it here: https://oss.sonatype.org/content/groups/public/net/openhft/chronicle-map/3.1.4-alpha/ or from Maven Central (it's just released so it might take about an hour until Maven "see" it).

Beta release should follow in about 2-3 weeks, it will effectively be RC of a production release. Time of subsequent production release depends on stability of beta.
