### ISSUE TITLE
MapEventListener in Chronicle 3.1.x

### ISSUE THREAD

**Issue by Ganet** [OpenHFT/Chronicle-Map#50]
I have read the README.md file in https://github.com/OpenHFT/Chronicle-Map/tree/chronicle-map-3.1.4-alpha and I had a special look at: Customizing Chronicle Map behaviour and using listeners.

However all these listeners are listening **before** an entry operation happens, **before** a map operation happens or in the last case **when** a remote operation happens. I thought **MapEventListener** in some previous versions listened to events after they happened and I was curious about why the behavior was changed in this way.

I was interested in having multiple Java processes in the same machine, each one listening to events after they happen in a ChronicleMap but I am not sure this is currently possible, as the listening happens before.

Kind Regards

**Comment by leventov** [comment]
I wouldn't call the Chronicle Map 3's constomization SPI "listeners", because it's something more powerful. It's a way to alter the key-value store behavior. You could do any action, before the actual operation, after the operation, cancel the operation under some conditions, etc. See how [BiMap](https://github.com/OpenHFT/Chronicle-Map#bimap) could be implemented.

You could have

    class MyEntryOperations<K, V> implements MapEntryOperations<K, V, Void> {
        @Override
        public Void insert(MapAbsentEntry<K,V> absentEntry, Data<V> value) {
            // do anything before the insert operation here.
            absentEntry.doInsert(value);
            // do anything after the insert operation here.
            return null;
        }
        
        // the same idea:
        public Void remove(MapEntry<K,V> entry) { ... }
        public Void replaceValue(MapEntry<K, V> entry, Data<V> newValue) { ... }
    }

Note that you obviously cannot listen on one process to the actions (inserts/udpates/removes), that happen in the different process. If you need something like this, you should constantly iterate the Chronicle Map in the "listening" process, with reading/updating some flags/timestamps, that are fields of the Map's value type. E. g.:
```
interface MyValue {
    boolean isInserted();
    void setInserted(boolean inserted);
    
    CharSequence getValue();
    void setValue(CharSequence value);
}
```

On insertion process side:

```
try (Closeable handle = map.acquireContext(key, myValue)) {
    myValue.setInserted(true);
    myValue.setValue(value);
}
```

Listening:
```
while (true) {
    map.forEach((k, myValue) -> {
        if (myValue.isInserted()) {
            backup(k, myValue.getValue());
            myValue.setInserted(false):
        }
    });
    Thread.sleep(...);
}
```

**Comment by peter-lawrey** [comment]
I would call them "interceptors" as they intercept the operation and can
perform actions before and/or after the operation.

**Comment by Ganet** [comment]
Thanks a lot for the quick reply! Very helpful insight.

Kind Regards
