### ISSUE TITLE
Not an issue, a question about replication (how to trigger relication)

### ISSUE THREAD

**Issue by zhyhang** [OpenHFT/Chronicle-Map#57]
When using the following code increasing long value, how to trigger replication?
```java
LongValue v=DataValueClasses.newDirectInstance(LongValue.class);
try (Closeable c = map.acquireUsingLocked(k, v)) {
    v.addAtomicValue(1024);
}
```
The map initilization code:

```java
		try {
			File f = new File(STORAGE_FILE);
			TcpTransportAndNetworkConfig tcpConfig = TcpTransportAndNetworkConfig
					.of(port, new InetSocketAddress(remoteHost, port)).heartBeatInterval(2L, TimeUnit.SECONDS)
					.autoReconnectedUponDroppedConnection(true);
			ChronicleMapBuilder<String, LongValue> mapBuilder = ChronicleMapBuilder
					.of(String.class, LongValue.class).entries(3000000L).replication(identifier, tcpConfig);
			map = mapBuilder.createPersistedTo(f);
		} catch (Exception e) {
			...
		}
```

Tanks!

**Comment by leventov** [comment]
Some observations:
 - Try to cache the reusable value object, `DataValueClasses.newDirectInstance(LongValue.class)`. By creating it each time right before the operation, you are killing the purpose of `*Using` operations. Cache value objects in fields or `ThreadLocal`s.
 - Under `acquireUsingLocked()` (Chronicle Map 2) and `acquireContext()` (Chronicle Map 3) using atomic updates of values makes no sense, because such operations (try-with-resources) are already mutually excluded. By using atomic value updates, you could reduce exclusiveness of Chronicle Map - level locks (and durations these locks are held), preserving integrity on entry level by atomic updates, e. g:

 ```java
 LongValue v = getDirectLongValue(); // field or ThreadLocal
 map.acquireUsing(key, v);
 // lock scope shortened, map level lock already released,
 // so concurrent updater may already come in. They will be
 // synchronized by atomic operation.
 v.addAtomicValue(1024);
 ```

 or even:

 ```java
 // done premilinarily, to ensure each key of interest is already in the map
 // with some default value
 LongValue v = getHeapValue();
 v.setValue(0);
 for (K key : keys) {
     map.put(key, v);
 }

 // main op
 LongValue v = getDirectLongValue(); // field or ThreadLocal
 // Comparing to the previous pattern, here even value acquisition is
 // parallelized (getUsing(), i. e. read locks doesn't exclude each other in Chronicle Map)
 map.getUsing(key, v);
 v.addAtomicValue(1024);
 ```
 - What the context (`acquireUsingLocked()`) is useful indeed is triggering replication, this is done in `Closeable.close()` method which is called implicitly in the end of try-with-resources block. So the answer to your question -- *replication should be already triggered in your snippet*. If you observe different behaviour (you think replication is not triggered) -- this requires more input to investigate (and this would be a bug)
