### ISSUE TITLE
get method returns null from ChronicleMap<String,UUID> on second access

### ISSUE THREAD

**Issue by reaster** [OpenHFT/Chronicle-Map#58]
I'm generating forward and reverse String-UUID maps using an UUIDObjectSerializer. If I run two identical tests, the second test fails on both version 2.1.2 and 3.1.5-alpha of ChronicleMap. This code replicates the error: 

```java
import static java.util.stream.Collectors.toMap;

import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

import net.openhft.chronicle.map.ChronicleMap;
import net.openhft.chronicle.map.ChronicleMapBuilder;
import net.openhft.lang.io.Bytes;
import net.openhft.lang.io.serialization.ObjectSerializer;

public class ChronicleMapBug
{
	File mapFile = new File("string-to-uuid.dat");
	File reverseMapFile = new File("uuid-to-string.dat");

	public static void main(String...args)
	{
        Map<String,UUID> map = new HashMap<>();
        map.put("AA", UUID.randomUUID());
        map.put("AB", UUID.randomUUID());
        map.put("BA", UUID.randomUUID());
        map.put("BB", UUID.randomUUID());
		try {
			ChronicleMapBug test = new ChronicleMapBug();
			test.writeMapAndReverseMap(map);
			test.test1(map);
			test.test2(map);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void writeMapAndReverseMap(Map<String,UUID> data) throws IOException
	{
		if (mapFile.exists())
			mapFile.delete();
		if (reverseMapFile.exists())
			reverseMapFile.delete();
		
		try ( 
				ChronicleMap<String,UUID> map = ChronicleMapBuilder.of(String.class, UUID.class)
        			.objectSerializer( new UUIDObjectSerializer() )
        			.averageKeySize(2)
        			.constantValueSizeBySample(UUID.randomUUID())
        			.entries(data.size())
        			.createPersistedTo(mapFile); 
				ChronicleMap<UUID,String> reverseMap = ChronicleMapBuilder.of(UUID.class, String.class)
	        		.objectSerializer( new UUIDObjectSerializer() )
	        		.averageValueSize(2)
	        		.constantKeySizeBySample(UUID.randomUUID())
	        		.entries(data.size())
	        		.createPersistedTo(reverseMapFile); 
		) {
			
			map.putAll(data);
			Map<UUID,String> reverse = data.keySet().stream().collect(toMap( k -> data.get(k), k -> k));
			reverseMap.putAll( reverse);
		}
	
	}

	public void test1(Map<String,UUID> data) throws IOException
	{
		try ( 
				ChronicleMap<String,UUID> map = ChronicleMapBuilder.of(String.class, UUID.class)
					.objectSerializer( new UUIDObjectSerializer() )
					.createPersistedTo(mapFile); 
				ChronicleMap<UUID,String> reverseMap = ChronicleMapBuilder.of(UUID.class, String.class)
	        		.objectSerializer( new UUIDObjectSerializer() )
	        		.createPersistedTo(reverseMapFile); 
		) {
			System.out.println("first test passes:");
			UUID uuid = data.get("BB");
			System.out.println( "BB"+" == "+reverseMap.get(uuid));
			System.out.println( uuid+" == "+map.get("BB"));
		}
	}
	
	public void test2(Map<String,UUID> data) throws IOException
	{
		try ( 
				ChronicleMap<String,UUID> map = ChronicleMapBuilder.of(String.class, UUID.class)
	    			.objectSerializer( new UUIDObjectSerializer() )
	    			.createPersistedTo(mapFile); 
				ChronicleMap<UUID,String> reverseMap = ChronicleMapBuilder.of(UUID.class, String.class)
	        		.objectSerializer( new UUIDObjectSerializer() )
	        		.createPersistedTo(reverseMapFile); 
			) {
			System.out.println("second identical test fails:");
			UUID uuid = data.get("BB");
			System.out.println( "BB"+" == "+reverseMap.get(uuid));
			System.out.println( uuid+" == "+map.get("BB")); //returns null
			System.out.println("despite all data being present:");
			map.entrySet().forEach( e -> System.out.println(e.getKey()+"->"+e.getValue()));
		}
		
	}
	

	class UUIDObjectSerializer implements ObjectSerializer
	{
		public void writeSerializable(Bytes bytes, Object object, Class expectedClass) throws IOException
		{
			if (UUID.class.equals(object.getClass())) {
				UUID uuid = (UUID)object;
				final long msb = uuid.getMostSignificantBits();
				final long lsb = uuid.getLeastSignificantBits();
				bytes.writeLong(msb);
				bytes.writeLong(lsb);
			} else {
				throw new IOException("ObjectSerializer does not support: "+object);
			}
		}	
		public <T> T readSerializable(Bytes bytes, Class<T> expectedClass, T object) throws IOException, ClassNotFoundException
		{
			final long mostSigBits = bytes.readLong();
			final long leastSigBits = bytes.readLong();
			UUID uuid = mostSigBits == 0L && leastSigBits == 0L ? null : new UUID(mostSigBits, leastSigBits);
			if (uuid == null) {
				throw new IOException("ObjectSerializer does not support: "+expectedClass);
			}
			return (T) uuid;
		}
	}

}
```

**Comment by leventov** [comment]
Thank you, this was a bug, now fixed in both branches.

Also, see your test with improvements:  https://github.com/OpenHFT/Chronicle-Map/blob/6b7eb9914478fbad662c14f87e27d7ec7a5f3e80/src/test/java/net/openhft/chronicle/map/Issue58.java

 - Use `BytesMarshaller` instead of `ObjectSerializer` (in the upcoming Chronicle Map 3 beta this API is going to be slightly changed though)
 - Chronicle Map keys and values should *never* be `null`. Don't return `null` from deserializing methods, this is dangerous. (Internally, Map relies on the assumption that keys/values are not `null`).
 - Never omit key/value sizing and `entries()` configurations in Chronicle Map (in Chronicle Map 3 beta they will be obligatory, throwing `IllegalStateException` if forgotten to configure).

**Comment by reaster** [comment]
Thanks for the quick fix and pointers.

Just a quick comment on the 3.x design - I'm maintaining hundreds of  Chronicle Maps as read-only resources. If specifying entreis() is always a requirement, I'd be forced to store these values somewhere. I'd be nice have a read-only flag baked into the builder and subsequent relaxed config requirements for this common use-case.

Awesome library! Thanks for all your hard work.

**Comment by leventov** [comment]
Size of the map determines some data structure dimensions (number of segments, capacity of a segment tier) that cannot change after the data structure creation. I. e. Chronicle Map doesn't "rehash" as an ordinary hash table. After a rehash oan rdinary hash table has exactly the same structure, as if it is created with the required capacity from the beginning. Chronicle Map is different. It is able to "grow" (add chained tiers to overflowed segments), but this ability is *exceptional* mechanism, with the alternative to fail with `IllegalStateException("Chronicle Map overflow")` (what Chronicle Map 2 does), and "grown" Chronicle Map is times slower than the Chronicle Map created with the right capacity from the beginning.

If you don't know the Map sizes, and accessing the created Chronicle Maps dominates over construction, I could recommend to build the Map first (probably not Chronicle Map, e. g. an ordinary `ConcurrentHashMap`), and when it is filled with the data, re-create the Map with number of entries configured properly.

When you access the existing Chronicle Map (`.createPersistedTo(file)` when the file is already existing) structural and serialization configurations to the `ChronicleMapBuilder` are irrelevant, because they should anyway be taken from the existing file, for correctness. Behavioural configurations (`MapEntryOperations`, `MapMethods`, replication endpoint addresses, `TimeProvider`, `putReturnsNull()`, etc.) could be different for each Chronicle Map "view" (in different JVMs, or even within the same JVM), and should be configured properly.

The recommendation that you always should configure even structural settings comes from the major pattern, when you create a persisted map and access existing *by the same java code*, creating a file, if accessing for the first time, or access existing. That is why the same method `createPersistedTo()` serves these two purposes, too.

It doesn't matter, if the accessed existing Chronicle Map is used as read-only or updated, because it doesn't affect the existing structure.

So yes, I should ensure that when the existing map is accessed the `entries()` configuration is optional, or if configured, is the same as existing.

I added two reminders for myself after this issue, https://higherfrequencytrading.atlassian.net/browse/HCOLL-406 and https://higherfrequencytrading.atlassian.net/browse/HCOLL-407, thanks for raising these questions.
