### ISSUE TITLE
Detect and attempt recovery automatically

### ISSUE THREAD

**Issue by panghy** [OpenHFT/Chronicle-Map#79]
In a persisted, concurrent access environment, processes that died or gets killed might leave around locks (most notably observed by processes restarting and getting blocked in ChronicleMap read lock acquisition frames). The fix seems to be to use createOrRecoverPersistedTo() in order to fix up the file. The catch here is that the code comments suggest that this should be done only by one process. This means that human intervention is required in order to ensure that no other clients of the file is active and recovery is attempted with an external tool (since calling that method every time would seem dangerous, "At the moment this method is called and executed, no other thread or process should be mapping to the given file, and trying to access the given file.").

Ideally, if ChronicleMap can detect stale locks and discard them (seems to be the most common issue), enforce a timeout for such locks, automatically recover the file if an exclusive lock is possible, or perhaps even simply complain when the map loads that something is wrong (read locks held by a non-existing process instead of hanging on read lock acquisitions perhaps?), it would allow systems that rely on ChronicleMap to run with much less manual intervention. More dangerously, it is not clear to the system if a segment of a ChronicleMap is silently "immutable" due to stale locks and only until the code accesses them does it block forever.

**Comment by leventov** [comment]
Sure, there is a room for improvement in this aspect. A hard part is that apparently there is no single solution that works well for all use cases, but abstracting this part of the implementation and making it configurable is hard.

> Ideally, if ChronicleMap can detect stale locks and discard them (seems to be the most common issue), enforce a timeout for such locks

Just for reference, what Chronicle Map 2 do is grabbing lock after 2 seconds of waiting. This approach has proven to be very fragile because if the JVM process which is currently holding a lock hits garbage collection, lock may easily remain held for more than 2 seconds, and any other sensible predefined timeout too (unlikely waiting on a lock for 5 minutes is better than error.)

> read locks held by a non-existing process instead of hanging on read lock acquisitions perhaps?

The problem is, that multiple processes could simultaneously lock a single segment (each on read lock level). We cannot store all their process IDs in a segment header, but is any of those processes dies, it will remain the segment inaccessible for exclusive locks.

...Well, while writing this I realized that there are some reasonable tradeoffs, for example specifying explicit cap on a number of concurrent accessing processes (4-16) and storing accessing process IDs in a tiny list in segment header.. I will think about it.

---

> it would allow systems that rely on ChronicleMap to run with much less manual intervention.

Current workaround might be to have a supplimentary file along with a map file, locking the file in shared mode on `createPersistedTo()` calls, unlocking on `map.close()`, locking in exclusive mode on `createOrRecoverPeristedTo()`, and demoting the lock to shared, after this call returns.

**Comment by peter-lawrey** [comment]
In the past, we used a timeout of about 10 seconds to detect which a lock
probably has been retained too long. This is useful if you have a process
die while another process is using it. i.e. you don't need to restart any
other process.  Perhaps we could have an option to do this. Do you think
this would work for you?

**Comment by panghy** [comment]
I suppose throwing an exception here or there is probably more acceptable than having a map lock up (and seeing that it's in some code that's waiting on a read lock and knowing that it's probably a stale lock issue).

I guess even with a supplementary file, other processes would still be holding the shared lock and there needs to be some mechanism to tell them that they need to close the map so that another process can come in and do recovery. There seems to be a need to signal across processes anyways.

**Comment by leventov** [comment]
> I suppose throwing an exception here or there is probably more acceptable than having a map lock up (and seeing that it's in some code that's waiting on a read lock and knowing that it's probably a stale lock issue).

Well, this is what is currently done. We are not blocking forever. We throw exception after 1 minute of waiting.

**Comment by peter-lawrey** [comment]
I think the option to force-clear the lock on such a timeout would make
cleaning up these locks easier (too easy ?)

**Comment by panghy** [comment]
I think as long as there's a mechanism by which locks that are held for an unreasonably long time (perhaps a minute or even more) would be invalidated. It's more of an issue that it throws but the map stays in the broken state. My previous message about throwing an exception here and there refers to exceptions that get thrown from spurious locks that are lost in favor of some self-healing.

Thanks for looking into this.

**Comment by minborg** [comment]
We have added file locking to protect concurrent invocation of recovery operations. If there is someone willing to sponsor the proposals mentioned above, please reopen this issue.
