### ISSUE TITLE
about the max entries of Chronicale Map

### ISSUE THREAD

**Issue by piaoxijun** [OpenHFT/Chronicle-Map#80]
Hi,
I'm using Chronicale Map 2.4.X nowadays.
I found something  suspicious. the process is like this

`new a map with max entries 10000`
`insert key 0-10000`
`map.clear()`
`insert key 10000-20000`
`map.clear()`
`insert key 20000-30000`
`map.clear()`

and I get the Exception
`Exception in thread "main" java.lang.IllegalStateException`
`at net.openhft.chronicle.map.ShortShortMultiMap.nextPos(ShortShortMultiMap.java:225)`
`at net.openhft.chronicle.map.ReplicatedChronicleMap$Segment.putWithoutLock(ReplicatedChronicleMap.java:1227)`
`at net.openhft.chronicle.map.ReplicatedChronicleMap$Segment.put(ReplicatedChronicleMap.java:1064)`
`at net.openhft.chronicle.map.ReplicatedChronicleMap.put(ReplicatedChronicleMap.java:353)`

Does that mean I can only use limited(10000 or 30000) keys even the entries in the map are removed when I set  the max number(10000)?

**Comment by leventov** [comment]
In Chronicle Map 2.x, if replication is ON, entries are never actually removed from the data structure, they are just marked as "deleted". This is needed for replication reconciliation purposes.

This issue is resolved in Chronicle Map 3, see https://higherfrequencytrading.atlassian.net/browse/HCOLL-227
