### ISSUE TITLE
Using Chronicle Map 3.9.1 and Chronicle Queue 4.5.5 in same project (no OSGI)

### ISSUE THREAD

**Issue by mikomarrache** [OpenHFT/Chronicle-Map#90]
Hi,

I have a modular application. Module A uses Chronicle Queue 4.5.5 and module B uses Chronicle Map 3.9.1. Which version of every library should be on the classpath?

Currently, I followed the assumption that higher version is better to resolve a conflict. Therefore I end up with the following classpath:

net.openhft:chronicle-queue:4.5.5
net.openhft:chronicle-map:3.9.1
net.openhft:chronicle-threads:1.7.2 (instead of 1.6.1 as required by chronicle-map)
net.openhft:chronicle-core:1.7.2 (instead of 1.6.2, 1.3.0 as required by chronicle-map and chronicle-algorithms, respectively)
net.openhft:chronicle-wire:1.7.5 (instead of 1.6.2 as required by chronicle-map)
net.openhft:chronicle-bytes:1.7.3 (instead of 1.5.2, 1.6.1, 1.2.3 as required by chronicle-values, chronicle-map and chronicle-algorithms, respectively)

Building a map with 3.9.1 is fine since it is a different module i.e. no conflict with queue libraries. However, when another module creates a map with the previously created file, I get a lot of the following errors:

2016-08-03 14:25:20,377 ERROR [main] [net.openhft.chronicle.map.impl.CompiledMapIterationContext] - Wrong number of entries counter for tier with index 1974, stored: 60, should be: 0
2016-08-03 14:25:20,377 ERROR [main] [net.openhft.chronicle.map.impl.CompiledMapIterationContext] - wrong lowest free chunk for tier with index 1974, stored: 358, should be: 0

What should I do?

Note that I don't use OSGi therefore I can't isolate libraries for every module...

Thanks,
Mickael

**Comment by mikomarrache** [comment]
Ok - it looks like the error is related to the fact I used a different config when creating and opening the map.

**Comment by leventov** [comment]
@mikomarrache - has the issue gone, when you started to configure map in the same way?

Apparently you are using `ChronicleMapBuilder.createOrRecoverPersistedTo()` to create a map in "a different module".

If a different module runs in the same JVM process, you shouldn't do this (open a same persisted Chronicle Map twice), [as said in the tutorial](https://github.com/OpenHFT/Chronicle-Map#user-content-single-chroniclemap-instance-per-jvm).

If a different module belongs to a *different* JVM process, note that you cannot call `createOrRecoverPersistedTo()` to open a Chronicle Map, if the involved modules (hence JVMs) run concurrently, as stated in the [`Recovery`](https://github.com/OpenHFT/Chronicle-Map#recovery) section of the tutorial:

> `.recoverPersistedTo()` needs to access the Chronicle Map exclusively. If a concurrent process is accessing the Chronicle Map while another process is attempting to perform recovery, result of operations on the accessing process side, and results of recovery are unspecified. The data could be corrupted further. You must ensure no other process is accessing the Chronicle Map store when calling for `.recoverPersistedTo()` on this store.

(Note that `createOrRecoverPersistedTo()` delegates to `recoverPersistedTo()` by the specification, so the above comes to `createOrRecoverPersistedTo()` as well.)

You can see a recent question about an issue that could appear if you *do* call `createOrRecoverPersistedTo()` while another process already accessing a map: http://stackoverflow.com/a/38614626

<hr>

Chronicle Map recovery was designed to be a way to recover maps only *in exceptional conditions*:

> If a process, accessing a persisted Chronicle Map, terminated abnormally: crashed, SIGKILLed, or terminated because the host operating system crashed, or the machine lost power, the Chronicle Map might remain in an inaccessible or corrupted state. When the Chronicle Map is opened next time from another process, it should be done via .recoverPersistedTo() method in ChronicleMapBuilder. Unlike createPersistedTo(), this method scans all memory of Chronicle Map store for inconsistencies, if some found, it cleans them up.

When you open a map with `createOrRecoverPersistedTo()` or `recoverPersistedTo()` methods after neither of the *exceptional* events listed above happened, the only thing you protect against is disk data corruption (that is guaranteed to never happen with some RAID systems) or main memory bit rot, that theoretically could happen, but
 - do you really think that your entire system is safe against disk bit rot/RAM bit rot? If not, protecting Chronicle Map's memory alone doesn't seem meaningful.
 - anyway, you are not protected agains such things after recovery procedure completes and you already use a map.

So effectively recovering maps "for any case", under normal conditions, is pointless, while it is *very* expensive computationally, and prone to mistakes like yours (diverged configurations, recovery while a concurrent process already has the map opened, etc.)

The suggested way to open Chronicle Maps is to detect exceptional conditions listed above (abnormal JVM process termination, abnormal machine termination) and recover Maps only they are the case, and using plain `createPersistedTo()` otherwise

**Comment by mikomarrache** [comment]
I misunderstood the docs - I will use createPersistedTo() as you suggested.
Using the same configuration, the errors disappeared.

Thanks
